[package]
name = "tinytga"
version = "0.3.2"
description = "No-std, low memory footprint TGA image loader"
authors = ["James Waples <james@wapl.es>"]
edition = "2018"
repository = "https://github.com/embedded-graphics/tinytga"
documentation = "https://docs.rs/tinytga"
categories = ["embedded", "no-std", "multimedia::images"]
keywords = ["graphics", "embedded-graphics", "tga", "targa", "image"]
readme = "./README.md"
license = "MIT OR Apache-2.0"
exclude = [
    ".travis.yml",
    ".gitignore",
]

[badges]
circle-ci = { repository = "embedded-graphics/embedded-graphics", branch = "master" }

[dev-dependencies]
paste = "1.0"

[dependencies.nom]
version = "5.1.0"
default-features = false

[dependencies.embedded-graphics]
# version = "=0.7.0-alpha.1"
# TODO: Remove when a new e-g alpha is released
git = "https://github.com/embedded-graphics/embedded-graphics"
branch = "new-repo"
